### ISSUE TITLE
 rm -rf /var/lib/apt/lists/* everywhere

### ISSUE THREAD

**Issue by StyXman** [dooman87/melbourne-map#1]
Your `Dockerfile`s have that gem in them. i think what you want to do is `sudo apt clean` to flush downloaded packages.

**Comment by dooman87** [comment]
Thanks for pointing this out @StyXman.

I think originally I found that recommendation here - https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#apt-get

I'll try to replace it with apt-get clean and will see what the results will be.

**Comment by zstadler** [comment]
According to https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run

> Official Debian and Ubuntu images automatically run `apt-get clean`, so explicit invocation is not required.
